### ISSUE TITLE
Is this a go library for data packages

### ISSUE THREAD

**Issue by rufuspollock** [the42/datapackage#1]
Hi, just stumbled across this and it looks like a go library for data packages which is very exciting!

Could you confirm? And would you like to list on http://data.okfn.org/tools/?

**Comment by the42** [comment]
Hi, yes indeed, however it is not extensively tested and not fully complete, i.e. automatic detection of mime types is not implemented, but otherwise it should work. Would make sense to list it on http://data.okfn.org/tools/, thank you!

**Comment by rufuspollock** [comment]
@the42 definitely would make sense to list on http://data.okfn.org/tools - please go ahead and do an edit to that page (if you click improve this page github should take you through the edit / fork / pull you need to do).
